// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtVfNXWoC15YAQVCLQr94voTqHW3DhpYA',
    appId: '1:688748571808:web:2437477341790cd8536dc5',
    messagingSenderId: '688748571808',
    projectId: 'sadak-ede10',
    authDomain: 'sadak-ede10.firebaseapp.com',
    storageBucket: 'sadak-ede10.firebasestorage.app',
    measurementId: 'G-VF45BMP42T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArYWk11p671v9hUCHHI4XdM0nUGbfIRFc',
    appId: '1:688748571808:android:addef110f1bcacb4536dc5',
    messagingSenderId: '688748571808',
    projectId: 'sadak-ede10',
    storageBucket: 'sadak-ede10.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaabF2FCAD97r2B_WpxAfuQ1HE7EXCg_U',
    appId: '1:688748571808:ios:dcd6e55eb0636efb536dc5',
    messagingSenderId: '688748571808',
    projectId: 'sadak-ede10',
    storageBucket: 'sadak-ede10.firebasestorage.app',
    iosBundleId: 'com.example.sadak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaabF2FCAD97r2B_WpxAfuQ1HE7EXCg_U',
    appId: '1:688748571808:ios:dcd6e55eb0636efb536dc5',
    messagingSenderId: '688748571808',
    projectId: 'sadak-ede10',
    storageBucket: 'sadak-ede10.firebasestorage.app',
    iosBundleId: 'com.example.sadak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtVfNXWoC15YAQVCLQr94voTqHW3DhpYA',
    appId: '1:688748571808:web:9a9a1c7c7a0ec798536dc5',
    messagingSenderId: '688748571808',
    projectId: 'sadak-ede10',
    authDomain: 'sadak-ede10.firebaseapp.com',
    storageBucket: 'sadak-ede10.firebasestorage.app',
    measurementId: 'G-98VHLKCXQJ',
  );
}
